logging:
  level:
    io:
      spring:
        cloud:
          samples: DEBUG

fortune:
  fallbackFortune: Your fortune is of your own making.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
